// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBymRqaJl8XK_t_mRQwyJTWFjBlVcVTQkQ',
    appId: '1:468745855150:web:f0e48fe540814d741a4d3f',
    messagingSenderId: '468745855150',
    projectId: 'you-it',
    authDomain: 'you-it.firebaseapp.com',
    storageBucket: 'you-it.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2mrALM9IrVFoLhIGZu5A-JTiehr2O-sY',
    appId: '1:468745855150:android:23b9bac8a060e2921a4d3f',
    messagingSenderId: '468745855150',
    projectId: 'you-it',
    storageBucket: 'you-it.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvXKXl-OmafuTXWj-xafYoarTSlJ3GpyA',
    appId: '1:468745855150:ios:c8225db3f68712b71a4d3f',
    messagingSenderId: '468745855150',
    projectId: 'you-it',
    storageBucket: 'you-it.appspot.com',
    iosClientId: '468745855150-62ml0b83etullee34shrqmoh02le4lno.apps.googleusercontent.com',
    iosBundleId: 'com.example.youIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvXKXl-OmafuTXWj-xafYoarTSlJ3GpyA',
    appId: '1:468745855150:ios:c8225db3f68712b71a4d3f',
    messagingSenderId: '468745855150',
    projectId: 'you-it',
    storageBucket: 'you-it.appspot.com',
    iosClientId: '468745855150-62ml0b83etullee34shrqmoh02le4lno.apps.googleusercontent.com',
    iosBundleId: 'com.example.youIt',
  );
}
